### ISSUE TITLE
Add dark theme

### ISSUE THREAD

**Issue by gmiclotte** [gmiclotte/gear-optimizer#10]
Can add Blaze's dark theme.

Should also properly style the things that are not properly styled, which is probably everything, but especially buttons and scroll bars.

**Comment by Zhinjio** [comment]
I'd like to help with this if you don't mind some collaboration.

**Comment by gmiclotte** [comment]
Ah right, completely forgot about this. Thanks for the offer, but I definitely won't be adding a dark theme. Nowadays I just advise everyone to use [dark reader](https://darkreader.org/) or some alternative :sweat_smile:
