### ISSUE TITLE
Would you consider exposing some things on the window object?

### ISSUE THREAD

**Issue by jshepler** [gmiclotte/gear-optimizer#107]
I've written a couple mods that works with GO to do a few things. On the GO side, I use bookmarklets to run some js to do whatever, but it seems webpack isn't exposing a method to access the modules so I'm reading/updating local storage.

I have basically put a web service inside the game and the bookmarklets sends requests to it. Currently, I'm sending loadouts to NGU, getting hack stats from NGU, and sending hack goals (targets) to NGU. When updating the data in local storage, I reload the page so that app is using the updated data.

This works, but it's a bit clunky.

Would you consider exposing something on the window object that I could use instead of reading/updating local storage? Optimally, it should let me update values in a way that would cause react to re-render appropriately.

**Comment by gmiclotte** [comment]
Hello, I have exposed the state of the App instance to `window.appState` in v0.9.1. You can now use the handlers defined in src/containers/App.js, e.g.,
- to equip item 75:
```{js}
appState.handleEquipItem(75);
```
- to change R power in hack page to 1e9:
```{js}
let hackstats = appState.hackstats;
hackstats.rpow = 1e9;
appState.handleSettings('hackstats', hackstats);
```

Using the handlers should re-render as expected.

Hope this helps!

**Comment by jshepler** [comment]
Excellent, thank you.

**Comment by jshepler** [comment]
![image](https://github.com/gmiclotte/gear-optimizer/assets/1145213/9a74088d-d398-4b61-aa9d-766f92bee77d)

**Comment by gmiclotte** [comment]
Oops, looks like that only kept the initial (=empty) state, and only the handlers were properly exposed.

I made a change in v0.9.2, so the handlers reside in `window.appHandlers`, and the actual state in `window.appState`, now the previous example becomes
```{js}
let hackstats = appState.hackstats; // access from appState
hackstats.rpow = 1e9;
appHandlers.handleSettings('hackstats', hackstats); // modify with appHandlers
```

If you modify the state (`window.appState`) directly, then changes will not stick and no rerendering will be done, to save the changes you can do `appHandlers.handleSaveStateLocalStorage(appState)`, and to rerender you have to reload. If you use the handlers to make changes, then everything should work as expected.

And `appState.savedequip` should now show what you expect.

**Comment by jshepler** [comment]
Perfect, working as expected. Thanks for quick fix.
