### ISSUE TITLE
Gear priority dropdown formatted is messed up on dark mode

### ISSUE THREAD

**Issue by scrattan6856** [gmiclotte/gear-optimizer#110]
![Gear Optimizer — Mozilla Firefox 7_15_2024 3_16_50 PM](https://github.com/user-attachments/assets/0ba3265a-6edf-463b-8983-112e438d6caa)

Broken on both firefox and microsoft edge.

**Comment by gmiclotte** [comment]
Thanks for letting me know. Completely forgot dark mode was a thing tbh. I'll have a look.

**Comment by gmiclotte** [comment]
Should be fixed in v0.9.6.
