### ISSUE TITLE
Magitech chestplate icon

### ISSUE THREAD

**Issue by alston13r** [gmiclotte/gear-optimizer#113]
The magitech icon on the site is the first image, the one from the game is the second image.
![image](https://github.com/user-attachments/assets/9ac93cc8-4fcf-40bb-9ed7-b5c29371e7c5)
![image](https://github.com/user-attachments/assets/d6596aa2-218a-4bc1-b7d9-6b893de7521c)

**Comment by alston13r** [comment]
#114 made a pull request :)

**Comment by gmiclotte** [comment]
Thanks a lot for the feedback and the PR!
