### ISSUE TITLE
"Disable unowned" toggle not working, import not updating gear levels

### ISSUE THREAD

**Issue by Nimapode** [gmiclotte/gear-optimizer#115]
Tested on Firefox v133.0.3 and Edge v131.0.2903.86

The website still imports the correct zone and titan version information, but unowned gear is not disabled, and gear levels are all set to 100.

**Comment by gmiclotte** [comment]
Hello


I cannot reproduce this issue. Please ensure you are on the latest version of the optimizer (v0.10.0 at the time of writing). You can check the live version in the _About_ tab.

If the issue persists after updating, please try the following:
- Retry the import in a fresh state (e.g., using an incognito/private browsing mode).
- Provide a save file for testing.
- Check for errors in the browser's developer console and share any error messages. To access the dev console:
  - On Windows/Linux: Press Ctrl+Shift+I or F12.
  - On Mac: Press Cmd+Option+I.


This is the import behavior I observe with the unowned check:
![window 24-12-13 08-26-21](https://github.com/user-attachments/assets/d8d8227f-3c51-4edc-b909-1a1ee3a210d3)
This is the expected dev console log:
![select 24-12-13 08-36-38](https://github.com/user-attachments/assets/c83dab1b-3a38-4042-8265-f03f191c0cf6)

**Comment by Nimapode** [comment]
Yes this is on the most recent v0.10.0, I'm getting this uncaught typeError upon loading
![image](https://github.com/user-attachments/assets/549560ec-0edd-470f-9bd5-fd0f170c74c7)

It's still happening on private tabs, I've also tried deleting cookies, refreshing the tab, different browser, etc.
A further note, this seems to only be an issue with a raw save, as I just tested it with an exported save from ngusav.es and it worked just fine! This may just be an issue on my end, especially if you can't reproduce the issue.

**Comment by Nimapode** [comment]
I think I've figured out how to reproduce the issue, if i have the "submit highscores" setting set to "off" it doesn't update gear correctly

**Comment by gmiclotte** [comment]
Thanks for the feedback! Can you send me a save file on which it breaks? Then I can have a look at what exactly goes wrong.

**Comment by Nimapode** [comment]
Of course, here you go!

[NGUSave-Build-1260-December-13-21-12.txt](https://github.com/user-attachments/files/18123488/NGUSave-Build-1260-December-13-21-12.txt)

**Comment by gmiclotte** [comment]
Thanks a lot!

Should be fixed in v0.10.1 now.

Apparently your save data contains a phantom 10th accessory slot, containing a null value. After loading the data in the game it showed only 9 slots, so I figure this 10th slot is a quirk of the save data formatting. I added a null check to handle this.

**Comment by Nimapode** [comment]
Oh weird! thank you for your help with this!
