### ISSUE TITLE
Save slot naming

### ISSUE THREAD

**Issue by Timeslice42** [gmiclotte/gear-optimizer#12]
I'm sure this is already on your list somewhere, but can we get naming for the equipment loadout *or* alternatively could it save the priorities/acc slot counts with the save slot?

**Comment by gmiclotte** [comment]
Not entirely sure what the best way to handle this is, but it would be a good addition . 

Could show the priorities when saved loadout is expanded. Could add a button to load those priorities, or couple the loading to the `load save` button. Maybe get rid of some buttons and put it all in a modal.

**Comment by gmiclotte** [comment]
There's now a button to load the priorities that were set when the loadout was saved. Not going to add naming.
