### ISSUE TITLE
Make wishes 0-based not 1-based

### ISSUE THREAD

**Issue by PaulWoitaschek** [gmiclotte/gear-optimizer#27]
Because on NGU they are 0-based too.

**Comment by gmiclotte** [comment]
They actually are, but for some reason I made the default wish 1. That is of course confusing, so that'll be changed.

**Comment by PaulWoitaschek** [comment]
When I input `0`, it prints "Unknown value". I assumed because the default is 1 and 0 shows an unknown value, that it's 1-based. Is that only because there are no stats for wish#0?

**Comment by gmiclotte** [comment]
Don't have the base cost yet for wishes 0, 58, and 62. Only started working on this after I had already completed wish 0. Will definitely add wish 0 soon though, someone gave me the raw data, just need to input it in my script. But, that's for after work :) .

**Comment by PaulWoitaschek** [comment]
What about creating a distinct error message?

`No stats for for Wish %s yet`
vs
`Invalid wish id`
