### ISSUE TITLE
Wish Picker

### ISSUE THREAD

**Issue by PaulWoitaschek** [gmiclotte/gear-optimizer#28]
I would love to have a feature where I can input my current levels of all wishes and the time I want to spend (i.e 12 hours) and it recommends me which wishes level the quickest to maximize the efficiency.

**Comment by PaulWoitaschek** [comment]
Looks great so far.
However I noticed that the times are different, looks like a bug:
<img width="771" alt="grafik" src="https://user-images.githubusercontent.com/743462/61446657-ce4a5800-a94f-11e9-998e-16465004f405.png">

**Comment by gmiclotte** [comment]
Oh I thought I had formatted that 240 minutes before pushing, apparently not. But 240 minutes is 4 hours, or what do you mean?

**Comment by gmiclotte** [comment]
Ah yes, that. The top uses same EMR ratio in the assignment as the ratio of available cap, while the bottom attempts to save as much R as possible. If you multiply EMR in both, then it is (almost) the same.

Probably going to remove the top one in the final version, I don't think it is ever the preferred method, but gathering some more feedback first.

**Comment by PaulWoitaschek** [comment]
![image](https://user-images.githubusercontent.com/743462/62805375-1d6b4f00-baf0-11e9-938a-c8e334af4de8.png)

To me it seems counter intuitive that energy and R3 are spent equally but magic is divided with a factor of 100.
Shouldnt there be sth like a limes function that outputs more uneven values for the optimal amount of free resources?

**Comment by gmiclotte** [comment]
You are entirely correct, however I was busy with other things, so I settled for this working, but suboptimal solution.

However, this should now be vastly improved in v0.1.9.

**Comment by gmiclotte** [comment]
Wish picker is not happening, I think anything else discussed here has been resolved, so I'll close this.
