### ISSUE TITLE
"Accessory slots" option is 3 less than it should be

### ISSUE THREAD

**Issue by thePalindrome** [gmiclotte/gear-optimizer#3]
The slots listed in the gui show 3 more slots than the "accessory slots" listing.

**Comment by thePalindrome** [comment]
Update, selecting "Optimize Equipment" fixed the slot count.

**Comment by gmiclotte** [comment]
This seems to occur when loading a saved loadout with a different number of slots. Will update number of slots to mirror the loaded loadout.

Does this happen in any other scenario?

**Comment by gmiclotte** [comment]
Loading loadouts and previous configurations with different numbers of acc slots should now be correctly handled.

**Comment by thePalindrome** [comment]
Confirmed fixed :+1:
