### ISSUE TITLE
Feature request: save priorities with gear set

### ISSUE THREAD

**Issue by jdknezek** [gmiclotte/gear-optimizer#33]
Hello! First off, thank you very much for creating this excellent tool!

In my personal usage, I like to have a few sets for different purposes (e.g. gold find to start a rebirth, then one for ITOPOD, and another for pushing/sniping). It would be nice if the save slot included not just the gear, but the priorities used to generate the gear as well. That way after you've acquired some more gear, you can just load the slot and re-optimize without having to remember the specific priorities and slot configuration used to generate that gear set.

Thank you!

**Comment by gmiclotte** [comment]
First off, you're welcome!

This has been requested before (#12), so (1) I'll close this and (2) I'll get to work and implement this, soon. Thanks for the suggestion!
