### ISSUE TITLE
Equipment not always optimizing

### ISSUE THREAD

**Issue by rtomek** [gmiclotte/gear-optimizer#37]
Here is my priority set: https://prnt.sc/q2syus

Rad-lands equipment is at level 100, beuc at level 36. I've noticed that if I set the leather jacket to the chest location and click 'optimize' that the leather jacket stays in its place. If I move the beuc to the chest location and click 'optimize' then the beuc stays in its place. I do not have any equipment locked.

**Comment by gmiclotte** [comment]
Odd, I can't reproduce this at all.

With BEUC at lvl 23 it equips the Leather Jacket, and with BEUC at 24 or higher (including 36) it equips BEUC, which is exactly what I would expect.

You're not somehow accidentally double clicking optimize?

**Comment by rtomek** [comment]
I just tried it again (didn't even refresh the page) and now it's working exactly as you describe and I would expect. It was definitely optimizing previously because my accessories were getting updated any my chest wasn't. Browser must have been acting funny or something because I can't reproduce it anymore :/

**Comment by gmiclotte** [comment]
Alright, that's great to hear!
