### ISSUE TITLE
Feature request: Loadout sharing

### ISSUE THREAD

**Issue by corvidae** [gmiclotte/gear-optimizer#38]
First off, thanks for this! NGUI is 0/10 unplayable without it. :)

We can save and load gear sets ourselves, but it would be nice to be able to get a static link that would include the current loadout's gear / levels as well as the total stats it provides so we could share them with others. Is this something that would be feasible?

**Comment by gmiclotte** [comment]
I have no idea how to do this, but it would be pretty cool if it worked. I'll look into this in the unspecified future, but can't promise if it'll ever make it in.

**Comment by gmiclotte** [comment]
Progress in v0.5.8:
You can import from URL (e.g. https://gmiclotte.github.io/gear-optimizer/#/loadout/A%20Stick&Cloth%20Boots ).
Exporting to URL is not yet implemented.
It purely concerns the loadout items, not the levels of each item, this will most likely not change.

**Comment by gmiclotte** [comment]
Should be working now in v0.5.24, there's a button in the save menu that opens a modal containing the current loadout and currenly selected saved loadout URIs.
