### ISSUE TITLE
Add documentation for advanced modifiers

### ISSUE THREAD

**Issue by jasperfirecai2** [gmiclotte/gear-optimizer#40]
I'm not sure advanced modifiers is finished yet, but quite some people ask in the discord about how to use it. It is quite straightforward once it clicks, but i feel like it would help users to have a small popup or paragraph in the how to about how to use advanced modifiers, and now current vs dedicated works.

**Comment by gmiclotte** [comment]
Added this (and some other changes) to the how-to in v0.5.1 (a8289a1). Let me know if something's missing or unclear still.

Thanks!
