### ISSUE TITLE
Not an issue, but a suggestion

### ISSUE THREAD

**Issue by Raisoshi** [gmiclotte/gear-optimizer#43]
Hey. I was thinking and I'd like to suggest a feature that checks all the available optimization options and lets you know when an item is obsolete(doesn't apply to any of the options). That would be neat

**Comment by gmiclotte** [comment]
Many of the optimization options are not relevant for large parts of the game, and with multiple priorities it might end up suggesting the use of items that would've been filtered in this way.

What you can do however, is save a loadout for all the priorities you do in fact care about, and then use the "mark unused items" button. This will put a red border around all the items that are not used by any of your loadouts. If you correctly configure the priorities for these loadouts, you can easily update all of them at once with the "optimize all saves" button.

I've been using it like that myself [with quite a few loadouts](https://i.imgur.com/ieudijE.png), and think it works fine for this purpose.
