### ISSUE TITLE
Feature request: Save data import

### ISSUE THREAD

**Issue by boozledorf** [gmiclotte/gear-optimizer#44]
I don't have the time to manually adjust every item I have every time I get a new one or level it up, or adjust my stat levels by hand whenever I make progress and want to change what I'm focusing on.  If there was a way to import the NGU save file and auto-populate everything, I'd actually want to use this.  Thanks!

**Comment by gmiclotte** [comment]
Could be convenient indeed. Someone's working on a [save file analyzer](ngusav.es), if that ends up working well I might base item importing on it, but for now it won't happen since I sadly don't have the time to do it all myself.

**Comment by gmiclotte** [comment]
with #61 you can now import the ngusav.es JSON

**Comment by boozledorf** [comment]
This looks good, thank you!  This'll definitely help, but I'm hoping it can be modified to also import Hack, Wish, and NGU stats as well.  But I'll definitely use this more now!
