### ISSUE TITLE
Equipment order causing non-optimal loadout

### ISSUE THREAD

**Issue by rtomek** [gmiclotte/gear-optimizer#47]
For my wish loadout, level 40 space boots are a definite upgrade over using my exile boots. They were already an upgrade at a lower level, as well. However, the exile boots are almost always chose over space boots when I click 'optimize'. 

I haven't looked into the code, but my assumption is that the outfit is selected prior to accessories. The only thing I can think of is that it's weighting the EM power very heavily when it selects the optimal boot, but once we have the rest of our gear set that EM power becomes relatively weak. It could be useful to have a way to force an additional iteration through the entire set of gear using the current loadout as baseline (or a 'slow' mode that will automatically continue to do so until no changes are made).

**Comment by gmiclotte** [comment]
Can't reproduce this. Can you export your local storage (in the about tab) and share that with me?

**Comment by rtomek** [comment]
File shared on discord

**Comment by gmiclotte** [comment]
Going to copy this here:

priorities are handled one-by-one, the succeeding priorities will not make changes to any items assigned so far

in this case, priority 2: wishes, slots: 0 will optimize for wish speed, using the items assigned so far (3 respawn accs), and only using gear slots, not accs; priority 4: wishes, slots: Infinity thus keeps the exile boots

i find it best to keep priority settings simple, in this case i'd just go for
1: respawn 3
2: wishes infinity
and that resulted in the correct loadout.

**Comment by rtomek** [comment]
Yes, in this instance I was using the following priorities:

1: respawn (3)
2: wishes (0)
3: vaired (0 currently)
4: wishes (infinity)

I noticed that the outfit definitely pulls in a certain order, and if I wanted to change a small number accessories (e.g. E/M/R3 bars for 1, 2, 3 items) it's easier to change a number prior to the infinity rather than having to keep track of how many wish slots there are. Note that there are some instances where the outfit actually does change because outfit DOES affect wishes, but not respawn so it will start choosing gear on priority 2.

Looking for a workaround, I tried the following priority setup:

1: respawn (3)
2: wishes (3-6)
3: vaired (0)
4: wishes (infinity)

and the result was better, but still not optimal. Going with:

1: respawn (3)
2: wishes (7)
3: vaired (0)
4: wishes (infinity)

got me to the optimal outfit configuration while still leaving me a few slots to play with while only having to adjust a single line. So perhaps consider this an FYI for more advanced usage. I guess it would be interesting to have an advanced setting where you can choose which stage(s) the outfit will also be prioritized alongside accessories, then there would be less requirements to count how many slots are going to be used by later priorities when setting earlier priorities.
