### ISSUE TITLE
All Pendants and Looties are shown, regardless of settings

### ISSUE THREAD

**Issue by greenswe** [gmiclotte/gear-optimizer#48]
![chrome_2020-04-06_17-25-58](https://user-images.githubusercontent.com/61507142/78575496-bd1de000-782b-11ea-920f-ea3db564b284.png)

**Comment by gmiclotte** [comment]
Should be fixed with 3ccd56343d6d2a4d19f173389f23862b589b5683

**Comment by gmiclotte** [comment]
Fix is deployed in v0.6.1.

Thanks for reporting!

**Comment by greenswe** [comment]
It is now fixed.
