### ISSUE TITLE
Sky seems borked

### ISSUE THREAD

**Issue by Zhinjio** [gmiclotte/gear-optimizer#49]
![download](https://user-images.githubusercontent.com/4079037/78576315-ba9a9680-77e9-11ea-88fb-2358b64a1698.png)

**Comment by gmiclotte** [comment]
Missing icons for items 434 and 449.

Thanks for reporting

**Comment by Zhinjio** [comment]
Can I provide any assistance?

**Comment by gmiclotte** [comment]
Fixed in 2a4c0448e962fc508028d3a9c457c6010cbf16c7
Deployed in v0.6.2
