### ISSUE TITLE
Incorrect item stats

### ISSUE THREAD

**Issue by thePalindrome** [gmiclotte/gear-optimizer#5]
- [x] swap stealthy chest bars
- [x] r3 power and bars are swapped for tophat 
- [x] skip card em pow got the extra 0
- [x] bv head and boots
- [x] Add My Pink Heart
- [x] BDW head gold drop, level 8 has 1296% but only half that in optimizer
- [x] Numerical boots has 8k% base, but it's actually 10k% base
- [x] OH quest drop
- [x] GM Wand PT 10x too low
- [x] Purple Heart?
- [x] Walderp chests toughness
- [x] Party boots don't have mpow?
- [x] CCOD toughness
- [x] UUG's special ring beard stat is much too high
- [x] The Clown Hat has its power listed as 12k, but actually has 120k
- [x] The Anime Figure's Ebars is set too high
- [x] The Calculator's base EM bars stat should be 6k%

**Comment by gmiclotte** [comment]
Base stats should be fixed, so please keep reporting those when you encounter them, thanks a lot.

More editing options for items would not be a bad idea, there's plenty of room in the edit-item modal.

**Comment by gmiclotte** [comment]
For the record, 10,740% at 79 translates to 10,740 / 1.79 * 2 = 12,000 at level 100.

Edited top post to keep track of (required) changes in a central location.

**Comment by gmiclotte** [comment]
Related to #4, changes in stats will not translate to currently equiped items, or saved loadouts.

**Comment by thePalindrome** [comment]
Yeah, my attempts to use the console to hotfix it didn't really work, since I can't seem to find the context where ITEM_LIST is actually living in, and editing the localStorage via the console doesn't work, since it saves out when I reload the page.

A quick and dirty way that *should* work would be stripping the `base` object from each item when we save it out, that way the base'll be regenned on reload (plus, why do we actually need to save that?)

**Comment by gmiclotte** [comment]
The objects shouldn't be saved, but I was so busy figuring out how to get anything working that I forgot to think about proper design :stuck_out_tongue:
Refactoring it as soon as I find the time.

**Comment by NiceGuyAndersson** [comment]
"The Candy Cane of Destiny" seems to have incorrect Toughness

**Comment by gmiclotte** [comment]
Moved the item stat editing suggestion to #6 
Reserving this issue purely for incorrect or missing stats

**Comment by CGrinder87** [comment]
Beardverse Head and Boots have incorrect stats.
Head toughness at lvl 100 is 24k instead of 22k.
Boots power at lvl 100 is 2.4k instead of 2.2k.

**Comment by gmiclotte** [comment]
Thanks for reporting!

**Comment by elspood** [comment]
Stealthy Chest has Energy Bars + EM Bars, not Magic Bars + EM Bars.

**Comment by gmiclotte** [comment]
Thanks, fixed in the next version.

**Comment by gmiclotte** [comment]
Wrong stats are entirely resolved with commit 60e39ac. Until the next update, of course.
