### ISSUE TITLE
Quest Drop to include Respawn gear

### ISSUE THREAD

**Issue by silent1b** [gmiclotte/gear-optimizer#51]
Both idle and active questing modes benefit from respawn gear.
It would need the nude respawn (seconds) to calculate accurately as 1 second (or 0.8 if active with mysterious red liquid) is added to the respawn (seconds).
`divider×100×items×(respawn+1) / (3×drop)`
https://ngu-idle.fandom.com/wiki/Questing

So for comparing idle Quest Drop rates
`(nude_respawn_sec × (1 - respawn_reduction%) + 1) / drop`

**Comment by gmiclotte** [comment]
Been putting this off because I really need to rework the input layout before adding even more input fields. (Also because I wouldn't use it :sweat_smile:.) But, I can see it being useful so I guess I'll do this next time I work on this.

And thanks for including the math :smiley:.

**Comment by gmiclotte** [comment]
Turns out this is a bit more work than I had in mind, if I ever get around to reworking priorities (#8 ) I'll be sure to incorporate this
