### ISSUE TITLE
Feature Request: Use ngusav.es export JSON as input for all values and gear

### ISSUE THREAD

**Issue by Zhinjio** [gmiclotte/gear-optimizer#54]
The save analyzer now has the ability to export a big ol' JSON file of everything. It contains all your gear as well as current stats (NGU values, etc). It would be lovely if you could use this file to automatically import/update all the current gear levels, NGU levels, etc etc etc.

**Comment by gmiclotte** [comment]
#61 does most of this, if there are any specific requests of imports I can look at it
