### ISSUE TITLE
Add gray heart set bonus to hacks page

### ISSUE THREAD

**Issue by ThierryBotty** [gmiclotte/gear-optimizer#59]
The hacks page should have a checkbox for gray heart set bonus.  There is a blue heart maxed checkbox, so I wonder why the gray heart bonus is not applied there as well.

**Comment by gmiclotte** [comment]
Hi

GH set bonus is part of hack speed already, so I don't think it adds much to add a toggle for it.

**Comment by ThierryBotty** [comment]
[Here are some screenshots.](https://imgur.com/a/wFv3NgO)

The set bonus isn't applied on the hacks page, according to my stats. If I change the 13.2 into 16.5 in the calculator (which is 13.2*1.25), then the calculation is correct for all of the hacks. I took wish hack just as an example but it holds true for all hacks. 

I have the GH item as lvl 100 on the gear page, so I am not sure where the problem lies unless I am missing something else here.

**Comment by gmiclotte** [comment]
You have to enter hack speed from the stat breakdowns/misc page. That breakdown should include grey heart set bonus. Now it looks like you entered the hack hack bonus as hack speed.
