### ISSUE TITLE
New loadout slots are missing...

### ISSUE THREAD

**Issue by L3thal1ty** [gmiclotte/gear-optimizer#64]
It used to be that I could set up a loadout, choose a name, and save it. Doing so would give me a new unnamed save to set up a new loadout on. This new loadout slot seems to be missing now. I am stuck with the 5 loadouts I have, and I can't set up a new one, only modify existing ones. Is this by design, or accident?

**Comment by gmiclotte** [comment]
This is a bug, no idea where it suddenly comes from, but you're the second tot report this in the span of a few days. Haven't been able to replicate it though.

Anyway, export your local storage in the about tab, this is just a backup in case the following messes something up.
Then run the following code in the browser console and reload the page, that should fix it by adding a new empty slot.

```
let tmp = JSON.parse(localStorage["gear-optimizer-state"]).savedequip;
tmp.push(JSON.parse("{\"weapon\":[10000,10000],\"head\":[10001],\"armor\":[10002],\"pants\":[10003],\"boots\":[10004],\"accessory\":[10005,10005,10005,10005,10005,10005,10005,10005,10005,10005,10005,10005,10005,10005,10005,10005],\"other\":[1000,1001]}"));
localStorage["gear-optimizer-state"] = JSON.stringify({
    ...JSON.parse(localStorage["gear-optimizer-state"]),
    savedequip: tmp,
});
```

**Comment by L3thal1ty** [comment]
Thanks, that fixed it.
