### ISSUE TITLE
JSON reader doesn't update the NGU speeds

### ISSUE THREAD

**Issue by Ragnatz** [gmiclotte/gear-optimizer#67]
I've been using the JSON reader to get the NGU data an Energy/Magic Cap data so it's easier to update my next values. However, I noticed that, even though the time said 1440 minutes, I was finishing in a few hours. I decided to check the upper values with my latest save read, and it turns out that my speeds were way off. I suspect those are the values I put in when I first did my inputs manually.

**Comment by rvazarkar** [comment]
That information isn't available in the save, it depends on tons of factors

**Comment by gmiclotte** [comment]
As rvazarkar said, the NGU speed information is not contained in the save, and computing it from the save is a whole other mess, so this won't be added.
