### ISSUE TITLE
Gear optimizer uses inaccessible hearts

### ISSUE THREAD

**Issue by grenierdx** [gmiclotte/gear-optimizer#69]
In optimizing gear for power and toughness, the pink and rainbow hearts are assigned to my loadout even though I can't get them -- I haven't beaten Godmother yet. The gray, pink, and rainbow hearts should be locked until "Highest Zone" is at or beyond the appropriate titan.

**Comment by gmiclotte** [comment]
You can actually get the rainbow heart before Godmother through one of the mtx packs.
I'd suggest you simply disable (right-click -> disable) the hearts though.
