### ISSUE TITLE
Use JSON files exported from NGU-save-parser

### ISSUE THREAD

**Issue by tex0l** [gmiclotte/gear-optimizer#89]
Since NGUSav.es doesn't work anymore, especially with build 1.260, I made the [NGU-Save-parser](https://github.com/AxesOfEvil/NGU-save-parser) work with build 1.260 up to sadistic :)

However, the JSON it outputs is incompatible with the one consumed by gear-optimizer.

Anyone knows how complex it might be to import from this JSON ?

**Comment by tex0l** [comment]
All right, changed my mind, I reimplemented the JSON export from the raw save file in JS, see PR https://github.com/gmiclotte/gear-optimizer/pull/90

**Comment by gmiclotte** [comment]
Merged #90, thanks a lot !

**Comment by tex0l** [comment]
You're much welcome :)
